	CREATE TABLE EXEMPLO_01 (
	ID INT,
	COLUNA1 VARCHAR(10),
	COLUNA2 VARCHAR(10),
	COLUNA3 VARCHAR(10),
	COLUNA4 VARCHAR(10));




	INSERT INTO EXEMPLO_01 VALUES(1,'A','B','C','D');
	INSERT INTO EXEMPLO_01 VALUES(2,'A','B','D','D');
	INSERT INTO EXEMPLO_01 VALUES(3,'A','B','C','D');
	INSERT INTO EXEMPLO_01 VALUES(4,'A','B','C','D');
	INSERT INTO EXEMPLO_01 VALUES(5,'A','B','C','D');
	INSERT INTO EXEMPLO_01 VALUES(6,'A','B','C','D');
	INSERT INTO EXEMPLO_01 VALUES(7,'A','C','C','D');
	INSERT INTO EXEMPLO_01 VALUES(8,'A','C','C','D');
	INSERT INTO EXEMPLO_01 VALUES(9,'A','C','C','D');
	INSERT INTO EXEMPLO_01 VALUES(10,'A','C','C','D');
	INSERT INTO EXEMPLO_01 VALUES(11,'A','C','C','D');


	/*CASO DE USO:
		
		VOCÊ PRECISA OBTER O NUMERO DE REGISTROS DE VALOR DO TIPO 'A' E TIPO 'B' DA COLUNA1.
		ANTES ERA NECESSÁRIO FAZER DOIS COUNTS DENTRO DA QUERY PRINCIPAL
		
		EXEMPLO: */
			SELECT DISTINCT 
				(SELECT COUNT(COLUNA2) FROM EXEMPLO_01 WHERE COLUNA2 = 'B') AS COLUNA2_COUNT_A,
				(SELECT COUNT(COLUNA2) FROM EXEMPLO_01 WHERE COLUNA2 = 'C') AS COLUNA2_COUNT_B
			FROM EXEMPLO_01;
    
	/* PORÉM PODEMOS FAZER SEM USAR SUBSELECTS, PARA ISSO USAMOS A FUNÇÃO PARTITION
	
		EXEMPLO: */
	
    SELECT DISTINCT 
        COLUNA2,
        COUNT(*) OVER (PARTITION BY COLUNA2 ) as COLUNA2_COUNT
    FROM EXEMPLO_01     
    
	
	/* A FUNÇÃO PARTITION ZERA O CONTADOR SEMPRE QUE O REGISTRO MUDA DE VALOR*/